[base]
Port=":8888"
BaseURL="http://xray/"
Debug=true

[mysql]
DBHost="localhost:3306"
DBUsername="test"
DBPassword="test"
DBName="xray"

[wechat]
CorpID=""
CorpSecret=""
AccessTokenUrl="https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=%s&corpsecret=%s"
SendMsgUrl="https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=%s"
AgentID=1000002

[admin]
InviteCode = ""