[base]
Port=":8888"
BaseURL="http://xray/"
WebRoot="./vulinfo"
Debug=true

[mysql]
DBHost="localhost:33060"
DBUsername="root"
DBPassword="root"
DBName="Xray"

[wechat]
CorpID="ww5143d142b9014209"
CorpSecret="gK2SJQ6Y6W0aRKEC9uxs44RDCRqhBQKi6SxusIWSxBY"
AccessTokenUrl="https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=%s&corpsecret=%s"
SendMsgUrl="https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=%s"
AgentID=1000002

[admin]
InviteCode = "annevinb!"